name: Build for sample-container-todo-app-java-maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        jdk: [ 8, 11, 16 ]
    name: Build
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.jdk }}
          distribution: 'adopt'
          cache: 'maven'
      - name: Collect Workflow Telemetry
        uses: thundra-io/workflow-telemetry-action@v1
      - name: Build with Maven
        run: ./mvnw clean install -DskipTests
      - name: "Get this job's run ID"
        id: get-job-id
        uses: actions/github-script@v6
        with:
          script: |
            const getJobId = async() => {
              const result = await github.rest.actions.listJobsForWorkflowRun({
                owner: context.repo.owner,
                repo: context.repo.repo,
                run_id: context.runId,
                per_page: 100,
              });
              const currentJobs = result.data.jobs.
                filter(it => it.status === 'in_progress' && it.runner_name === process.env.RUNNER_NAME);
              if (currentJobs && currentJobs.length) {
                return currentJobs[0].id;
              }
              return null;
            }
            for (let i = 0; i < 10; i++) {
              const currentJobId = await getJobId();
              if (currentJobId) {
                console.log("Current job id:", currentJobId);
                return currentJobId;
              }
              await new Promise(r => setTimeout(r, 1000));
            }
      - name: "My job ID is ${{steps.get-job-id.outputs.result}}"
        run: >
          echo "get-job-id=${{steps.get-job-id.outputs.result}}"
      - name: "Runner name"
        id: runner-name
        uses: actions/github-script@v6
        with:
          script: |
            console.log(process.env.RUNNER_NAME)
